### PR TITLE
Dotnet implementation

### LINKED ISSUE #7: How to use apis for Fable
I am using Fable.SimpleHttp 2.1.0 with my fable project, but I could not find `Http.request`. How I can use them?
SimpleHttp issue1

### PR DESCRIPTION
**Pull request by stroborobo**
While looking into #7 I thought that it might be good to actually just move the basic dotnet implementations of Http.get/post to Http.send and change the method functions to use Http.send again. Since there are no dotnet tests in the repo this is not thoroughly tested.

I hope this is alright.

Fixes #7

### CODE REVIEW

**Comment by stroborobo** [comment]
Btw, HttpMethod does not have the `RequireQualifiedAccess` attribute, was that intended? The other unions do, just noticed.

**Comment by Zaid-Ajaj** [comment]
Looks really good @stroborobo! One thing I noticed is that the `Http.send` can still throw exceptions when compiled using dotnet. Can you please use a `try . . . catch` block around there

> I find it really weird that libraries throw exceptions in HTTP client where error handling is already a built-in part of the protocol using status codes

**Comment by stroborobo** [comment]
Sure, the return type of send is an HttpResponse though, so what would you like to get in case of errors? StatusCode = 0, responseText = exception.Message?

**Comment by Zaid-Ajaj** [comment]
Hmm I am not sure status code 0 says anything. If we assume that the only reason one gets an exception is when you call a non-existent url (DNS resolution exception) then it means the service is unavailable, in which case a status code of 503 is more appropriate don't you think?

**Comment by stroborobo** [comment]
I don't feel like we should mimic http where there is no http. Incidentally I messed up my CORS settings a few days ago and found out that the xhr does have a status of 0 in that case. Seems like it just doesn't set the property though, or any property indicating the error for that matter, so empty responseText, too.

Since the dotnet implementation is meant to copy the behaviour of the fable one, I think we should do the same thing. So I'd catch HttpRequestExceptions and return a basically empty response.

In a future 3.x version Http.send could maybe return an `Async<Result<HttpResponse, string>>` or something similar, question is though where to get any details on the error. Btw, for future reference, there are event handlers for error/loaded etc, but they don't appear to provide better information.

**Comment by Zaid-Ajaj** [comment]
> Since the dotnet implementation is meant to copy the behaviour of the fable one, I think we should do the same thing. So I'd catch HttpRequestExceptions and return a basically empty response.

Yeah I guess you are right, mimicking the Fable equivalent should be good enough as this is made to support Fable type providers

**Comment by Zaid-Ajaj** [comment]
Awesome, looks ready to me, can I merge?

**Comment by stroborobo** [comment]
I'm done, yes 👍

**Comment by Zaid-Ajaj** [comment]
Published v2.4.0 and will be available soon on nuget, thanks a lot @stroborobo :fire:

**Comment by stroborobo** [comment]
Thank *you* for all the cool libs ❤️

**Comment by Zaid-Ajaj** [comment]
Thanks for the kind words, I am glad someone is actually using them 😄

**Pull request merged**
